targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        # type_overrides:
        #   CustomStringScalar:
        #     name: String
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          #
          # For usage information, reference the corresponding field in
          # `JsonSerializableGenerator`.
          # any_map: false
          # checked: false
          # create_factory: true
          # create_to_json: true
          # disallow_unrecognized_keys: false
          # explicit_to_json: false
          # field_rename: snake
          # generate_to_json_function: true
          # include_if_null: true
          # nullable: true
          # use_wrappers: false
