// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.gql.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(GAcceptEnterpriseAdministratorInvitationInput.serializer)
      ..add(GAcceptTopicSuggestionInput.serializer)
      ..add(GAddAssigneesToAssignableInput.serializer)
      ..add(GAddCommentInput.serializer)
      ..add(GAddLabelsToLabelableInput.serializer)
      ..add(GAddProjectCardInput.serializer)
      ..add(GAddProjectColumnInput.serializer)
      ..add(GAddPullRequestReviewCommentInput.serializer)
      ..add(GAddPullRequestReviewInput.serializer)
      ..add(GAddPullRequestReviewThreadInput.serializer)
      ..add(GAddReactionInput.serializer)
      ..add(GAddStarInput.serializer)
      ..add(GArchiveRepositoryInput.serializer)
      ..add(GAuditLogOrder.serializer)
      ..add(GAuditLogOrderField.serializer)
      ..add(GCancelEnterpriseAdminInvitationInput.serializer)
      ..add(GChangeUserStatusInput.serializer)
      ..add(GCheckAnnotationData.serializer)
      ..add(GCheckAnnotationLevel.serializer)
      ..add(GCheckAnnotationRange.serializer)
      ..add(GCheckConclusionState.serializer)
      ..add(GCheckRunAction.serializer)
      ..add(GCheckRunFilter.serializer)
      ..add(GCheckRunOutput.serializer)
      ..add(GCheckRunOutputImage.serializer)
      ..add(GCheckRunType.serializer)
      ..add(GCheckStatusState.serializer)
      ..add(GCheckSuiteAutoTriggerPreference.serializer)
      ..add(GCheckSuiteFilter.serializer)
      ..add(GClearLabelsFromLabelableInput.serializer)
      ..add(GCloneProjectInput.serializer)
      ..add(GCloneTemplateRepositoryInput.serializer)
      ..add(GCloseIssueInput.serializer)
      ..add(GClosePullRequestInput.serializer)
      ..add(GCollaboratorAffiliation.serializer)
      ..add(GCommentAuthorAssociation.serializer)
      ..add(GCommentCannotUpdateReason.serializer)
      ..add(GCommitAuthor.serializer)
      ..add(GCommitContributionOrder.serializer)
      ..add(GCommitContributionOrderField.serializer)
      ..add(GContributionOrder.serializer)
      ..add(GConvertProjectCardNoteToIssueInput.serializer)
      ..add(GCreateBranchProtectionRuleInput.serializer)
      ..add(GCreateCheckRunInput.serializer)
      ..add(GCreateCheckSuiteInput.serializer)
      ..add(GCreateEnterpriseOrganizationInput.serializer)
      ..add(GCreateIpAllowListEntryInput.serializer)
      ..add(GCreateIssueInput.serializer)
      ..add(GCreateProjectInput.serializer)
      ..add(GCreatePullRequestInput.serializer)
      ..add(GCreateRefInput.serializer)
      ..add(GCreateRepositoryInput.serializer)
      ..add(GCreateTeamDiscussionCommentInput.serializer)
      ..add(GCreateTeamDiscussionInput.serializer)
      ..add(GDate.serializer)
      ..add(GDateTime.serializer)
      ..add(GDeclineTopicSuggestionInput.serializer)
      ..add(GDefaultRepositoryPermissionField.serializer)
      ..add(GDeleteBranchProtectionRuleInput.serializer)
      ..add(GDeleteDeploymentInput.serializer)
      ..add(GDeleteIpAllowListEntryInput.serializer)
      ..add(GDeleteIssueCommentInput.serializer)
      ..add(GDeleteIssueInput.serializer)
      ..add(GDeleteProjectCardInput.serializer)
      ..add(GDeleteProjectColumnInput.serializer)
      ..add(GDeleteProjectInput.serializer)
      ..add(GDeletePullRequestReviewCommentInput.serializer)
      ..add(GDeletePullRequestReviewInput.serializer)
      ..add(GDeleteRefInput.serializer)
      ..add(GDeleteTeamDiscussionCommentInput.serializer)
      ..add(GDeleteTeamDiscussionInput.serializer)
      ..add(GDeploymentOrder.serializer)
      ..add(GDeploymentOrderField.serializer)
      ..add(GDeploymentState.serializer)
      ..add(GDeploymentStatusState.serializer)
      ..add(GDiffSide.serializer)
      ..add(GDismissPullRequestReviewInput.serializer)
      ..add(GDraftPullRequestReviewComment.serializer)
      ..add(GDraftPullRequestReviewThread.serializer)
      ..add(GEnterpriseAdministratorInvitationOrder.serializer)
      ..add(GEnterpriseAdministratorInvitationOrderField.serializer)
      ..add(GEnterpriseAdministratorRole.serializer)
      ..add(GEnterpriseDefaultRepositoryPermissionSettingValue.serializer)
      ..add(GEnterpriseEnabledDisabledSettingValue.serializer)
      ..add(GEnterpriseEnabledSettingValue.serializer)
      ..add(GEnterpriseMemberOrder.serializer)
      ..add(GEnterpriseMemberOrderField.serializer)
      ..add(GEnterpriseMembersCanCreateRepositoriesSettingValue.serializer)
      ..add(GEnterpriseMembersCanMakePurchasesSettingValue.serializer)
      ..add(GEnterpriseServerInstallationOrder.serializer)
      ..add(GEnterpriseServerInstallationOrderField.serializer)
      ..add(GEnterpriseServerUserAccountEmailOrder.serializer)
      ..add(GEnterpriseServerUserAccountEmailOrderField.serializer)
      ..add(GEnterpriseServerUserAccountOrder.serializer)
      ..add(GEnterpriseServerUserAccountOrderField.serializer)
      ..add(GEnterpriseServerUserAccountsUploadOrder.serializer)
      ..add(GEnterpriseServerUserAccountsUploadOrderField.serializer)
      ..add(GEnterpriseServerUserAccountsUploadSyncState.serializer)
      ..add(GEnterpriseUserAccountMembershipRole.serializer)
      ..add(GEnterpriseUserDeployment.serializer)
      ..add(GFileViewedState.serializer)
      ..add(GFollowUserInput.serializer)
      ..add(GFundingPlatform.serializer)
      ..add(GGhCommitsData.serializer)
      ..add(GGhCommitsData_repository.serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef.serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_author
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_author_user
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_history
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes_author
          .serializer)
      ..add(
          GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes_author_user
              .serializer)
      ..add(
          GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes_status
              .serializer)
      ..add(
          GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_pageInfo
              .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__asCommit_status
          .serializer)
      ..add(GGhCommitsData_repository_defaultBranchRef_target__base.serializer)
      ..add(GGhCommitsData_repository_ref.serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit.serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_author.serializer)
      ..add(
          GGhCommitsData_repository_ref_target__asCommit_author_user.serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_history.serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_history_nodes
          .serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_history_nodes_author
          .serializer)
      ..add(
          GGhCommitsData_repository_ref_target__asCommit_history_nodes_author_user
              .serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_history_nodes_status
          .serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_history_pageInfo
          .serializer)
      ..add(GGhCommitsData_repository_ref_target__asCommit_status.serializer)
      ..add(GGhCommitsData_repository_ref_target__base.serializer)
      ..add(GGhCommitsReq.serializer)
      ..add(GGhCommitsVars.serializer)
      ..add(GGhIssuesData.serializer)
      ..add(GGhIssuesData_repository.serializer)
      ..add(GGhIssuesData_repository_issues.serializer)
      ..add(GGhIssuesData_repository_issues_nodes.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_author.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_comments.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_labels.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_labels_nodes.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_repository.serializer)
      ..add(GGhIssuesData_repository_issues_nodes_repository_owner.serializer)
      ..add(GGhIssuesData_repository_issues_pageInfo.serializer)
      ..add(GGhIssuesData_repository_owner.serializer)
      ..add(GGhIssuesReq.serializer)
      ..add(GGhIssuesVars.serializer)
      ..add(GGhOpenIssueData.serializer)
      ..add(GGhOpenIssueData_closeIssue.serializer)
      ..add(GGhOpenIssueData_closeIssue_issue.serializer)
      ..add(GGhOpenIssueData_reopenIssue.serializer)
      ..add(GGhOpenIssueData_reopenIssue_issue.serializer)
      ..add(GGhOpenIssueReq.serializer)
      ..add(GGhOpenIssueVars.serializer)
      ..add(GGhPullsData.serializer)
      ..add(GGhPullsData_repository.serializer)
      ..add(GGhPullsData_repository_owner.serializer)
      ..add(GGhPullsData_repository_pullRequests.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_author.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_comments.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_labels.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_labels_nodes.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_repository.serializer)
      ..add(GGhPullsData_repository_pullRequests_nodes_repository_owner
          .serializer)
      ..add(GGhPullsData_repository_pullRequests_pageInfo.serializer)
      ..add(GGhPullsReq.serializer)
      ..add(GGhPullsVars.serializer)
      ..add(GGhRepoData.serializer)
      ..add(GGhRepoData_repository.serializer)
      ..add(GGhRepoData_repository_defaultBranchRef.serializer)
      ..add(GGhRepoData_repository_defaultBranchRef_target__asCommit.serializer)
      ..add(GGhRepoData_repository_defaultBranchRef_target__asCommit_history
          .serializer)
      ..add(GGhRepoData_repository_defaultBranchRef_target__base.serializer)
      ..add(GGhRepoData_repository_forks.serializer)
      ..add(GGhRepoData_repository_issues.serializer)
      ..add(GGhRepoData_repository_languages.serializer)
      ..add(GGhRepoData_repository_languages_edges.serializer)
      ..add(GGhRepoData_repository_languages_edges_node.serializer)
      ..add(GGhRepoData_repository_licenseInfo.serializer)
      ..add(GGhRepoData_repository_owner.serializer)
      ..add(GGhRepoData_repository_primaryLanguage.serializer)
      ..add(GGhRepoData_repository_projects.serializer)
      ..add(GGhRepoData_repository_pullRequests.serializer)
      ..add(GGhRepoData_repository_ref.serializer)
      ..add(GGhRepoData_repository_ref_target__asCommit.serializer)
      ..add(GGhRepoData_repository_ref_target__asCommit_history.serializer)
      ..add(GGhRepoData_repository_ref_target__base.serializer)
      ..add(GGhRepoData_repository_refs.serializer)
      ..add(GGhRepoData_repository_refs_nodes.serializer)
      ..add(GGhRepoData_repository_releases.serializer)
      ..add(GGhRepoData_repository_repositoryTopics.serializer)
      ..add(GGhRepoData_repository_repositoryTopics_nodes.serializer)
      ..add(GGhRepoData_repository_repositoryTopics_nodes_topic.serializer)
      ..add(GGhRepoData_repository_stargazers.serializer)
      ..add(GGhRepoData_repository_watchers.serializer)
      ..add(GGhRepoReq.serializer)
      ..add(GGhRepoVars.serializer)
      ..add(GGhReposData.serializer)
      ..add(GGhReposData_user.serializer)
      ..add(GGhReposData_user_repositories.serializer)
      ..add(GGhReposData_user_repositories_nodes.serializer)
      ..add(GGhReposData_user_repositories_nodes_forks.serializer)
      ..add(GGhReposData_user_repositories_nodes_owner.serializer)
      ..add(GGhReposData_user_repositories_nodes_primaryLanguage.serializer)
      ..add(GGhReposData_user_repositories_nodes_stargazers.serializer)
      ..add(GGhReposData_user_repositories_pageInfo.serializer)
      ..add(GGhReposData_user_starredRepositories.serializer)
      ..add(GGhReposData_user_starredRepositories_nodes.serializer)
      ..add(GGhReposData_user_starredRepositories_nodes_forks.serializer)
      ..add(GGhReposData_user_starredRepositories_nodes_owner.serializer)
      ..add(GGhReposData_user_starredRepositories_nodes_primaryLanguage
          .serializer)
      ..add(GGhReposData_user_starredRepositories_nodes_stargazers.serializer)
      ..add(GGhReposData_user_starredRepositories_pageInfo.serializer)
      ..add(GGhReposReq.serializer)
      ..add(GGhReposVars.serializer)
      ..add(GGhUserData.serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization.serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization_membersWithRole
          .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems.serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__asRepository
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__asRepository_forks
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__asRepository_owner
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__asRepository_primaryLanguage
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__asRepository_stargazers
              .serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes__base
          .serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization_pinnedItems.serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__asRepository
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__asRepository_forks
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__asRepository_owner
              .serializer)
      ..add(
          GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__asRepository_primaryLanguage
              .serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__asRepository_stargazers.serializer)
      ..add(GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes__base.serializer)
      ..add(GGhUserData_repositoryOwner__asUser.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_contributionsCollection.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks_contributionDays.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_followers.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_following.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__asRepository.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__asRepository_forks.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__asRepository_owner.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__asRepository_primaryLanguage.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__asRepository_stargazers.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes__base.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories_nodes.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories_nodes_forks.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories_nodes_owner.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories_nodes_primaryLanguage.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_repositories_nodes_stargazers.serializer)
      ..add(GGhUserData_repositoryOwner__asUser_starredRepositories.serializer)
      ..add(GGhUserData_repositoryOwner__base.serializer)
      ..add(GGhUserReq.serializer)
      ..add(GGhUserVars.serializer)
      ..add(GGhUsersData.serializer)
      ..add(GGhUsersData_organization.serializer)
      ..add(GGhUsersData_organization_membersWithRole.serializer)
      ..add(GGhUsersData_organization_membersWithRole_nodes.serializer)
      ..add(GGhUsersData_organization_membersWithRole_pageInfo.serializer)
      ..add(GGhUsersData_repository.serializer)
      ..add(GGhUsersData_repository_stargazers.serializer)
      ..add(GGhUsersData_repository_stargazers_nodes.serializer)
      ..add(GGhUsersData_repository_stargazers_pageInfo.serializer)
      ..add(GGhUsersData_repository_watchers.serializer)
      ..add(GGhUsersData_repository_watchers_nodes.serializer)
      ..add(GGhUsersData_repository_watchers_pageInfo.serializer)
      ..add(GGhUsersData_user.serializer)
      ..add(GGhUsersData_user_followers.serializer)
      ..add(GGhUsersData_user_followers_nodes.serializer)
      ..add(GGhUsersData_user_followers_pageInfo.serializer)
      ..add(GGhUsersData_user_following.serializer)
      ..add(GGhUsersData_user_following_nodes.serializer)
      ..add(GGhUsersData_user_following_pageInfo.serializer)
      ..add(GGhUsersReq.serializer)
      ..add(GGhUsersVars.serializer)
      ..add(GGhViewerData.serializer)
      ..add(GGhViewerData_viewer.serializer)
      ..add(GGhViewerData_viewer_contributionsCollection.serializer)
      ..add(GGhViewerData_viewer_contributionsCollection_contributionCalendar.serializer)
      ..add(GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks.serializer)
      ..add(GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks_contributionDays.serializer)
      ..add(GGhViewerData_viewer_followers.serializer)
      ..add(GGhViewerData_viewer_following.serializer)
      ..add(GGhViewerData_viewer_repositories.serializer)
      ..add(GGhViewerData_viewer_starredRepositories.serializer)
      ..add(GGhViewerReq.serializer)
      ..add(GGhViewerVars.serializer)
      ..add(GGistOrder.serializer)
      ..add(GGistOrderField.serializer)
      ..add(GGistPrivacy.serializer)
      ..add(GGitObjectID.serializer)
      ..add(GGitSSHRemote.serializer)
      ..add(GGitSignatureState.serializer)
      ..add(GGitTimestamp.serializer)
      ..add(GHTML.serializer)
      ..add(GIdentityProviderConfigurationState.serializer)
      ..add(GInviteEnterpriseAdminInput.serializer)
      ..add(GIpAllowListEnabledSettingValue.serializer)
      ..add(GIpAllowListEntryOrder.serializer)
      ..add(GIpAllowListEntryOrderField.serializer)
      ..add(GIssueCommentOrder.serializer)
      ..add(GIssueCommentOrderField.serializer)
      ..add(GIssueFilters.serializer)
      ..add(GIssueOrder.serializer)
      ..add(GIssueOrderField.serializer)
      ..add(GIssueState.serializer)
      ..add(GIssueTimelineItemsItemType.serializer)
      ..add(GLabelOrder.serializer)
      ..add(GLabelOrderField.serializer)
      ..add(GLanguageOrder.serializer)
      ..add(GLanguageOrderField.serializer)
      ..add(GLinkRepositoryToProjectInput.serializer)
      ..add(GLockLockableInput.serializer)
      ..add(GLockReason.serializer)
      ..add(GMarkFileAsViewedInput.serializer)
      ..add(GMarkPullRequestReadyForReviewInput.serializer)
      ..add(GMergeBranchInput.serializer)
      ..add(GMergePullRequestInput.serializer)
      ..add(GMergeableState.serializer)
      ..add(GMilestoneOrder.serializer)
      ..add(GMilestoneOrderField.serializer)
      ..add(GMilestoneState.serializer)
      ..add(GMinimizeCommentInput.serializer)
      ..add(GMoveProjectCardInput.serializer)
      ..add(GMoveProjectColumnInput.serializer)
      ..add(GOauthApplicationCreateAuditEntryState.serializer)
      ..add(GOperationType.serializer)
      ..add(GOrderDirection.serializer)
      ..add(GOrgAddMemberAuditEntryPermission.serializer)
      ..add(GOrgCreateAuditEntryBillingPlan.serializer)
      ..add(GOrgRemoveBillingManagerAuditEntryReason.serializer)
      ..add(GOrgRemoveMemberAuditEntryMembershipType.serializer)
      ..add(GOrgRemoveMemberAuditEntryReason.serializer)
      ..add(GOrgRemoveOutsideCollaboratorAuditEntryMembershipType.serializer)
      ..add(GOrgRemoveOutsideCollaboratorAuditEntryReason.serializer)
      ..add(GOrgUpdateDefaultRepositoryPermissionAuditEntryPermission.serializer)
      ..add(GOrgUpdateMemberAuditEntryPermission.serializer)
      ..add(GOrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility.serializer)
      ..add(GOrganizationInvitationRole.serializer)
      ..add(GOrganizationInvitationType.serializer)
      ..add(GOrganizationMemberRole.serializer)
      ..add(GOrganizationMembersCanCreateRepositoriesSettingValue.serializer)
      ..add(GOrganizationOrder.serializer)
      ..add(GOrganizationOrderField.serializer)
      ..add(GPackageFileOrder.serializer)
      ..add(GPackageFileOrderField.serializer)
      ..add(GPackageOrder.serializer)
      ..add(GPackageOrderField.serializer)
      ..add(GPackageType.serializer)
      ..add(GPackageVersionOrder.serializer)
      ..add(GPackageVersionOrderField.serializer)
      ..add(GPinnableItemType.serializer)
      ..add(GPreciseDateTime.serializer)
      ..add(GProjectCardArchivedState.serializer)
      ..add(GProjectCardState.serializer)
      ..add(GProjectColumnPurpose.serializer)
      ..add(GProjectOrder.serializer)
      ..add(GProjectOrderField.serializer)
      ..add(GProjectState.serializer)
      ..add(GProjectTemplate.serializer)
      ..add(GPullRequestMergeMethod.serializer)
      ..add(GPullRequestOrder.serializer)
      ..add(GPullRequestOrderField.serializer)
      ..add(GPullRequestReviewCommentState.serializer)
      ..add(GPullRequestReviewDecision.serializer)
      ..add(GPullRequestReviewEvent.serializer)
      ..add(GPullRequestReviewState.serializer)
      ..add(GPullRequestState.serializer)
      ..add(GPullRequestTimelineItemsItemType.serializer)
      ..add(GPullRequestUpdateState.serializer)
      ..add(GReactionContent.serializer)
      ..add(GReactionOrder.serializer)
      ..add(GReactionOrderField.serializer)
      ..add(GRefOrder.serializer)
      ..add(GRefOrderField.serializer)
      ..add(GRegenerateEnterpriseIdentityProviderRecoveryCodesInput.serializer)
      ..add(GReleaseOrder.serializer)
      ..add(GReleaseOrderField.serializer)
      ..add(GRemoveAssigneesFromAssignableInput.serializer)
      ..add(GRemoveEnterpriseAdminInput.serializer)
      ..add(GRemoveEnterpriseIdentityProviderInput.serializer)
      ..add(GRemoveEnterpriseOrganizationInput.serializer)
      ..add(GRemoveLabelsFromLabelableInput.serializer)
      ..add(GRemoveOutsideCollaboratorInput.serializer)
      ..add(GRemoveReactionInput.serializer)
      ..add(GRemoveStarInput.serializer)
      ..add(GReopenIssueInput.serializer)
      ..add(GReopenPullRequestInput.serializer)
      ..add(GRepoAccessAuditEntryVisibility.serializer)
      ..add(GRepoAddMemberAuditEntryVisibility.serializer)
      ..add(GRepoArchivedAuditEntryVisibility.serializer)
      ..add(GRepoChangeMergeSettingAuditEntryMergeType.serializer)
      ..add(GRepoCreateAuditEntryVisibility.serializer)
      ..add(GRepoDestroyAuditEntryVisibility.serializer)
      ..add(GRepoPartData.serializer)
      ..add(GRepoPartData_forks.serializer)
      ..add(GRepoPartData_owner.serializer)
      ..add(GRepoPartData_primaryLanguage.serializer)
      ..add(GRepoPartData_stargazers.serializer)
      ..add(GRepoPartReq.serializer)
      ..add(GRepoPartVars.serializer)
      ..add(GRepoRemoveMemberAuditEntryVisibility.serializer)
      ..add(GReportedContentClassifiers.serializer)
      ..add(GRepositoryAffiliation.serializer)
      ..add(GRepositoryContributionType.serializer)
      ..add(GRepositoryInteractionLimit.serializer)
      ..add(GRepositoryInteractionLimitExpiry.serializer)
      ..add(GRepositoryInteractionLimitOrigin.serializer)
      ..add(GRepositoryInvitationOrder.serializer)
      ..add(GRepositoryInvitationOrderField.serializer)
      ..add(GRepositoryLockReason.serializer)
      ..add(GRepositoryOrder.serializer)
      ..add(GRepositoryOrderField.serializer)
      ..add(GRepositoryPermission.serializer)
      ..add(GRepositoryPrivacy.serializer)
      ..add(GRepositoryVisibility.serializer)
      ..add(GRequestReviewsInput.serializer)
      ..add(GRequestableCheckStatusState.serializer)
      ..add(GRerequestCheckSuiteInput.serializer)
      ..add(GResolveReviewThreadInput.serializer)
      ..add(GSamlDigestAlgorithm.serializer)
      ..add(GSamlSignatureAlgorithm.serializer)
      ..add(GSavedReplyOrder.serializer)
      ..add(GSavedReplyOrderField.serializer)
      ..add(GSearchType.serializer)
      ..add(GSecurityAdvisoryEcosystem.serializer)
      ..add(GSecurityAdvisoryIdentifierFilter.serializer)
      ..add(GSecurityAdvisoryIdentifierType.serializer)
      ..add(GSecurityAdvisoryOrder.serializer)
      ..add(GSecurityAdvisoryOrderField.serializer)
      ..add(GSecurityAdvisorySeverity.serializer)
      ..add(GSecurityVulnerabilityOrder.serializer)
      ..add(GSecurityVulnerabilityOrderField.serializer)
      ..add(GSetEnterpriseIdentityProviderInput.serializer)
      ..add(GSetOrganizationInteractionLimitInput.serializer)
      ..add(GSetRepositoryInteractionLimitInput.serializer)
      ..add(GSetUserInteractionLimitInput.serializer)
      ..add(GSponsorsTierOrder.serializer)
      ..add(GSponsorsTierOrderField.serializer)
      ..add(GSponsorshipOrder.serializer)
      ..add(GSponsorshipOrderField.serializer)
      ..add(GSponsorshipPrivacy.serializer)
      ..add(GStarOrder.serializer)
      ..add(GStarOrderField.serializer)
      ..add(GStatusState.serializer)
      ..add(GSubmitPullRequestReviewInput.serializer)
      ..add(GSubscriptionState.serializer)
      ..add(GTData.serializer)
      ..add(GTData_target__asCommit.serializer)
      ..add(GTData_target__asCommit_author.serializer)
      ..add(GTData_target__asCommit_author_user.serializer)
      ..add(GTData_target__asCommit_history.serializer)
      ..add(GTData_target__asCommit_history_nodes.serializer)
      ..add(GTData_target__asCommit_history_nodes_author.serializer)
      ..add(GTData_target__asCommit_history_nodes_author_user.serializer)
      ..add(GTData_target__asCommit_history_nodes_status.serializer)
      ..add(GTData_target__asCommit_history_pageInfo.serializer)
      ..add(GTData_target__asCommit_status.serializer)
      ..add(GTData_target__base.serializer)
      ..add(GTReq.serializer)
      ..add(GTVars.serializer)
      ..add(GTeamDiscussionCommentOrder.serializer)
      ..add(GTeamDiscussionCommentOrderField.serializer)
      ..add(GTeamDiscussionOrder.serializer)
      ..add(GTeamDiscussionOrderField.serializer)
      ..add(GTeamMemberOrder.serializer)
      ..add(GTeamMemberOrderField.serializer)
      ..add(GTeamMemberRole.serializer)
      ..add(GTeamMembershipType.serializer)
      ..add(GTeamOrder.serializer)
      ..add(GTeamOrderField.serializer)
      ..add(GTeamPrivacy.serializer)
      ..add(GTeamRepositoryOrder.serializer)
      ..add(GTeamRepositoryOrderField.serializer)
      ..add(GTeamRole.serializer)
      ..add(GTopicSuggestionDeclineReason.serializer)
      ..add(GTransferIssueInput.serializer)
      ..add(GURI.serializer)
      ..add(GUnarchiveRepositoryInput.serializer)
      ..add(GUnfollowUserInput.serializer)
      ..add(GUnlinkRepositoryFromProjectInput.serializer)
      ..add(GUnlockLockableInput.serializer)
      ..add(GUnmarkFileAsViewedInput.serializer)
      ..add(GUnmarkIssueAsDuplicateInput.serializer)
      ..add(GUnminimizeCommentInput.serializer)
      ..add(GUnresolveReviewThreadInput.serializer)
      ..add(GUpdateBranchProtectionRuleInput.serializer)
      ..add(GUpdateCheckRunInput.serializer)
      ..add(GUpdateCheckSuitePreferencesInput.serializer)
      ..add(GUpdateEnterpriseAdministratorRoleInput.serializer)
      ..add(GUpdateEnterpriseAllowPrivateRepositoryForkingSettingInput.serializer)
      ..add(GUpdateEnterpriseDefaultRepositoryPermissionSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanCreateRepositoriesSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanDeleteIssuesSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanDeleteRepositoriesSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanInviteCollaboratorsSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanMakePurchasesSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanUpdateProtectedBranchesSettingInput.serializer)
      ..add(GUpdateEnterpriseMembersCanViewDependencyInsightsSettingInput.serializer)
      ..add(GUpdateEnterpriseOrganizationProjectsSettingInput.serializer)
      ..add(GUpdateEnterpriseProfileInput.serializer)
      ..add(GUpdateEnterpriseRepositoryProjectsSettingInput.serializer)
      ..add(GUpdateEnterpriseTeamDiscussionsSettingInput.serializer)
      ..add(GUpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput.serializer)
      ..add(GUpdateIpAllowListEnabledSettingInput.serializer)
      ..add(GUpdateIpAllowListEntryInput.serializer)
      ..add(GUpdateIssueCommentInput.serializer)
      ..add(GUpdateIssueInput.serializer)
      ..add(GUpdateProjectCardInput.serializer)
      ..add(GUpdateProjectColumnInput.serializer)
      ..add(GUpdateProjectInput.serializer)
      ..add(GUpdatePullRequestInput.serializer)
      ..add(GUpdatePullRequestReviewCommentInput.serializer)
      ..add(GUpdatePullRequestReviewInput.serializer)
      ..add(GUpdateRefInput.serializer)
      ..add(GUpdateRepositoryInput.serializer)
      ..add(GUpdateSubscriptionInput.serializer)
      ..add(GUpdateTeamDiscussionCommentInput.serializer)
      ..add(GUpdateTeamDiscussionInput.serializer)
      ..add(GUpdateTopicsInput.serializer)
      ..add(GUserBlockDuration.serializer)
      ..add(GUserStatusOrder.serializer)
      ..add(GUserStatusOrderField.serializer)
      ..add(GX509Certificate.serializer)
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckAnnotationData)]), () => new ListBuilder<GCheckAnnotationData>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckRunOutputImage)]), () => new ListBuilder<GCheckRunOutputImage>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckRunAction)]), () => new ListBuilder<GCheckRunAction>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckRunAction)]), () => new ListBuilder<GCheckRunAction>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckSuiteAutoTriggerPreference)]), () => new ListBuilder<GCheckSuiteAutoTriggerPreference>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GDraftPullRequestReviewComment)]), () => new ListBuilder<GDraftPullRequestReviewComment>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GDraftPullRequestReviewThread)]), () => new ListBuilder<GDraftPullRequestReviewThread>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes)
          ]),
          () => new ListBuilder<GGhCommitsData_repository_defaultBranchRef_target__asCommit_history_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhCommitsData_repository_ref_target__asCommit_history_nodes)]), () => new ListBuilder<GGhCommitsData_repository_ref_target__asCommit_history_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhIssuesData_repository_issues_nodes)]), () => new ListBuilder<GGhIssuesData_repository_issues_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhIssuesData_repository_issues_nodes_labels_nodes)]), () => new ListBuilder<GGhIssuesData_repository_issues_nodes_labels_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhPullsData_repository_pullRequests_nodes)]), () => new ListBuilder<GGhPullsData_repository_pullRequests_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhPullsData_repository_pullRequests_nodes_labels_nodes)]), () => new ListBuilder<GGhPullsData_repository_pullRequests_nodes_labels_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhRepoData_repository_languages_edges)]), () => new ListBuilder<GGhRepoData_repository_languages_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhRepoData_repository_refs_nodes)]), () => new ListBuilder<GGhRepoData_repository_refs_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhRepoData_repository_repositoryTopics_nodes)]), () => new ListBuilder<GGhRepoData_repository_repositoryTopics_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhReposData_user_repositories_nodes)]), () => new ListBuilder<GGhReposData_user_repositories_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhReposData_user_starredRepositories_nodes)]), () => new ListBuilder<GGhReposData_user_starredRepositories_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes)]), () => new ListBuilder<GGhUserData_repositoryOwner__asOrganization_pinnableItems_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes)]), () => new ListBuilder<GGhUserData_repositoryOwner__asOrganization_pinnedItems_nodes>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks)
          ]),
          () => new ListBuilder<GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks_contributionDays)
          ]),
          () => new ListBuilder<GGhUserData_repositoryOwner__asUser_contributionsCollection_contributionCalendar_weeks_contributionDays>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUserData_repositoryOwner__asUser_pinnedItems_nodes)]), () => new ListBuilder<GGhUserData_repositoryOwner__asUser_pinnedItems_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUserData_repositoryOwner__asUser_repositories_nodes)]), () => new ListBuilder<GGhUserData_repositoryOwner__asUser_repositories_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUsersData_organization_membersWithRole_nodes)]), () => new ListBuilder<GGhUsersData_organization_membersWithRole_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUsersData_repository_stargazers_nodes)]), () => new ListBuilder<GGhUsersData_repository_stargazers_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUsersData_repository_watchers_nodes)]), () => new ListBuilder<GGhUsersData_repository_watchers_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUsersData_user_followers_nodes)]), () => new ListBuilder<GGhUsersData_user_followers_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GGhUsersData_user_following_nodes)]), () => new ListBuilder<GGhUsersData_user_following_nodes>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks)
          ]),
          () => new ListBuilder<GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(
                GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks_contributionDays)
          ]),
          () => new ListBuilder<GGhViewerData_viewer_contributionsCollection_contributionCalendar_weeks_contributionDays>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GTData_target__asCommit_history_nodes)]), () => new ListBuilder<GTData_target__asCommit_history_nodes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GIssueState)]), () => new ListBuilder<GIssueState>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>()))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
